"""Fill in more through autogenerate

Revision ID: 68bde12f9f49
Revises: 630e8a620280
Create Date: 2022-05-18 20:44:11.535454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68bde12f9f49'
down_revision = '630e8a620280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('id', sa.Integer(), nullable=False, primary_key=True))
    op.add_column('posts', sa.Column('title', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('content', sa.String(), nullable=False))
    op.create_unique_constraint("posts_id_unique_constraint", 'posts', ['id'])
    op.create_table('votes',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('post_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['post_id'], ['posts.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('user_id', 'post_id')
                    )

    op.add_column('users', sa.Column(
        'email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(
        timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint("users_email_unique_constraint", 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.drop_column('posts', 'content')
    op.drop_column('posts', 'title')
    op.drop_constraint('votes_post_id_fkey', 'votes')
    op.drop_column('posts', 'id')
    # op.drop_constraint("users_email_unique_constraint", 'users', type_='unique', )
    # op.drop_constraint("posts_id_unique_constraint", 'posts', type_='unique')
    op.drop_table('votes')
    # ### end Alembic commands ###
