"""Fill in even more through autogenerate

Revision ID: c19d0f4bf4d9
Revises: 68bde12f9f49
Create Date: 2022-05-18 21:09:30.654118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c19d0f4bf4d9'
down_revision = '68bde12f9f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
